export type State = {
	state: string;
	slug: string;
	code: string;
	nickname: string;
	website: string;
	admission_date: string;
	admission_number: number;
	capital_city: string;
	capital_url: string;
	population: number;
	population_rank: number;
	constitution_url: string;
	state_flag_url: string;
	state_seal_url: string;
	map_image_url: string;
	landscape_background_url: string;
	skyline_background_url: string;
	twitter_url: string | null;
	facebook_url: string | null;
};
